# Generated by Django 5.1.4 on 2025-01-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('admin', 'Admin'), ('responsable', 'Responsable')], default='agent', max_length=15),
        ),
    ]
