# Generated by Django 5.1.4 on 2025-01-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
