# Generated by Django 5.1.4 on 2025-01-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
