# Generated by Django 5.1.4 on 2025-01-31 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        ('users', '0007_clients_first_name_clients_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne',
            name='horaire',
        ),
        migrations.AddField(
            model_name='ligne',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligne',
            name='end_cutoff',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ligne',
            name='end_hour',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='ligne',
            name='start_cutoff',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ligne',
            name='start_hour',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='ligne',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='state',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='planning',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='users.clients'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Horaire',
        ),
    ]
