# Generated by Django 5.1.4 on 2025-02-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_remove_ligne_days_ligne_month_days_ligne_week_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ligne',
            name='selected_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='total_hours',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='end_cutoff',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='end_hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='month_days',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='start_cutoff',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='start_hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='week_days',
            field=models.CharField(max_length=20),
        ),
    ]
