# Generated by Django 5.1.4 on 2025-02-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_alter_ligne_agent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligne',
            name='agent_type',
            field=models.CharField(choices=[('Agent de sécurité confirmé', 'agent_securite_confirme'), ('Agent de sécurité magasin prévol', 'agent_securite_magasin_prevol'), ('Agent de sécurité filtrage', 'agent_securite_filtrage'), ('Agent de sécurité qualifié', 'agent_securite_qualifie'), ('Conducteur de chien', 'conducteur_chien'), ('Agent de sécurité SSIAP1', 'agent_securite_SSIAP1'), ('Agent de sécurité SSIAP2', 'agent_securite_SSIAP2'), ('Agent de sécurité SSIAP3', 'agent_securite_SSIAP3'), ('chef_de_site', 'Chef de site'), ('adjoint_chef_site', 'Adjoint chef de site'), ('chef_equipe', 'Chef d’équipe'), ('Agent mobile', 'agent_mobile'), ('chef_poste', 'chef_poste'), ('operateur_video_sct1', 'Opérateur vidéo SCT 1'), ('operateur_video_sct2', 'Opérateur vidéo SCT 2'), ('Agent rondier', 'agent_rondier')], max_length=100),
        ),
    ]
