# Generated by Django 5.1.4 on 2025-02-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_alter_ligne_agent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hour_salary', models.FloatField()),
                ('salary_type', models.CharField(choices=[('net', 'Net'), ('brute', 'Brute')], max_length=100)),
                ('minimal_hours', models.IntegerField()),
                ('maximal_hours', models.IntegerField(blank=True, null=True)),
                ('tenues', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.CharField(max_length=255)),
                ('experience', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='planning',
            name='conditions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='planning.conditions'),
        ),
    ]
