# Generated by Django 5.1.4 on 2025-02-17 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_conditions_planning_conditions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='state',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived'), ('en_cours', 'En cours')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='PlanningAgent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('refused', 'Refused'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('position', models.JSONField(blank=True, null=True)),
                ('nbr_heure', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning', to='planning.planning')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('planning', 'agent'), name='unique_planning_agent')],
                'unique_together': {('planning', 'agent')},
            },
        ),
    ]
