# Generated by Django 5.1.4 on 2025-01-11 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo_identity', models.CharField(max_length=255)),
                ('nss', models.CharField(max_length=50, unique=True)),
                ('card_number_pro', models.CharField(max_length=50, unique=True)),
                ('security_card_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('nub', models.CharField(blank=True, max_length=10, null=True)),
                ('agent_fonction', models.TextField(blank=True, null=True)),
                ('driver_licence_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('N', 'N')], default='N', max_length=2)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('diplomes', models.JSONField(blank=True, null=True)),
                ('experience', models.JSONField(blank=True, null=True)),
                ('tenues', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
