# Generated by Django 5.1.4 on 2025-01-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='agent_type',
            new_name='agent_fonction',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='security_card_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
