# Generated by Django 5.1.4 on 2025-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_agent_type_agentprofile_agent_fonction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=15),
        ),
    ]
