# Generated by Django 5.1.4 on 2025-01-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_agentprofile_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='ville',
            field=models.CharField(blank=True, default='paris', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('refused', 'Refused')], default='pending', max_length=15),
        ),
    ]
