# Generated by Django 5.1.4 on 2025-01-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_clients_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='last_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
