# Generated by Django 5.1.4 on 2025-02-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_remove_ligne_horaire_ligne_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne',
            name='days',
        ),
        migrations.AddField(
            model_name='ligne',
            name='month_days',
            field=models.CharField(default='YYYYNNNNYYYY', max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligne',
            name='week_days',
            field=models.CharField(default='112333', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ligne',
            name='end_cutoff',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='start_cutoff',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
