# Generated by Django 5.1.4 on 2025-02-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_remove_ligne_created_at_remove_ligne_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
    ]
