# Generated by Django 5.1.4 on 2025-02-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_planning_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligne',
            name='agent_type',
            field=models.CharField(choices=[('agent_securite_confirme', 'Agent de sécurité confirmé'), ('agent_securite_magasin_prevol', 'Agent de sécurité magasin prévol'), ('agent_securite_filtrage', 'Agent de sécurité filtrage'), ('agent_securite_qualifie', 'Agent de sécurité qualifié'), ('conducteur_chien', 'Conducteur de chien'), ('agent_securite_SSIAP1', 'Agent de sécurité SSIAP1'), ('agent_securite_SSIAP2', 'Agent de sécurité SSIAP2'), ('agent_securite_SSIAP3', 'Agent de sécurité SSIAP3'), ('Chef de site', 'chef_de_site'), ('Adjoint chef de site', 'adjoint_chef_site'), ('Chef d’équipe', 'chef_equipe'), ('agent_mobile', 'Agent mobile'), ('Chef de poste', 'chef_poste'), ('Opérateur vidéo SCT 1', 'operateur_video_sct1'), ('Opérateur vidéo SCT 2', 'operateur_video_sct2'), ('agent_rondier', 'Agent rondier')], max_length=100),
        ),
        migrations.AlterField(
            model_name='planning',
            name='state',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
