# Generated by Django 5.1.4 on 2025-02-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_alter_ligne_agent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne',
            name='isPausePaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planning',
            name='start_planning_date',
            field=models.DateTimeField(default='2025-02-02'),
            preserve_default=False,
        ),
    ]
