# Generated by Django 5.1.4 on 2025-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_ligne_ispausepaid_planning_start_planning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='start_planning_date',
            field=models.DateField(default='2025-02-01'),
        ),
    ]
