# Generated by Django 5.1.4 on 2025-02-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_alter_planning_start_planning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligne',
            name='agent_type',
            field=models.CharField(choices=[('agent_securite_confirme', 'Agent de sécurité confirmé'), ('agent_securite_magasin_prevol', 'Agent de sécurité magasin prévol'), ('agent_securite_filtrage', 'Agent de sécurité filtrage'), ('agent_securite_qualifie', 'Agent de sécurité qualifié'), ('conducteur_chien', 'Conducteur de chien'), ('agent_securite_SSIAP1', 'Agent de sécurité SSIAP1'), ('chef_equipe_SSIAP2', 'Chef d’équipe SSIAP2'), ('chef_site_SSIAP3', 'Chef de site SSIAP3'), ('agent_mobile', 'Agent mobile'), ('agent_rondier', 'Agent rondier'), ('chef_de_site', 'Chef de site'), ('adjoint_chef_site', 'Adjoint chef de site'), ('chef_equipe', 'Chef d’équipe'), ('chef_poste', 'Chef de poste'), ('operateur_video_sct1', 'Opérateur vidéo SCT 1'), ('operateur_video_sct2', 'Opérateur vidéo SCT 2')], max_length=100),
        ),
    ]
