# Generated by Django 5.1.4 on 2025-02-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_alter_planning_state_planningagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningagent',
            name='demande',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
