# Generated by Django 5.1.4 on 2025-02-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_planningagent_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningagent',
            name='agent_function',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
