# Generated by Django 5.1.4 on 2025-02-19 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_planningagent_agent_function'),
        ('users', '0007_clients_first_name_clients_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='users.agentprofile'),
        ),
    ]
