# Generated by Django 5.1.4 on 2025-03-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0016_alter_planningagent_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne',
            name='days_needs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
