# Generated by Django 4.2.10 on 2025-04-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_ligne_days_needs_alter_planning_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_date', models.DateField()),
                ('motiv', models.CharField(max_length=255)),
                ('absence_type', models.CharField(max_length=255)),
                ('is_justified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('planning_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_agent', to='planning.planningagent')),
            ],
        ),
    ]
