# Generated by Django 4.2.10 on 2025-04-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0019_alter_absences_is_justified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
