# Generated by Django 5.1.4 on 2025-01-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('admin', 'Admin'), ('responsable', 'Responsable'), ('client', 'Client')], default='agent', max_length=15),
        ),
    ]
